export const authRoutes = [
  {
    exact: true,
    path: '/',
    component: '@/pages/User/index',
    title: 'Nhân viên',
    routes: [],
    wrappers: ['@/layouts/Wrapper'],
  },
  {
    exact: true,
    path: '/user',
    component: '@/pages/User/index',
    title: 'Nhân viên',
    routes: [],
    wrappers: ['@/layouts/Wrapper'],
  },
  {
    exact: true,
    path: '/account',
    component: '@/pages/MyAccount/index',
    title: 'Thông tin cá nhân',
    routes: [],
    wrappers: ['@/layouts/Wrapper'],
  },
  {
    exact: true,
    path: '/user_detail/:id',
    component: '@/pages/UserEditAccount/index',
    title: 'Nhân viên',
    routes: [],
    wrappers: ['@/layouts/Wrapper'],
  },
  {
    exact: true,
    path: '/user_new/',
    component: '@/pages/UserNewAccount/index',
    title: 'Nhân viên',
    routes: [],
    wrappers: ['@/layouts/Wrapper'],
  },
  {
    exact: true,
    path: '/user_edit/:id',
    component: '@/pages/UserEditAccount/index',
    title: 'Nhân viên',
    routes: [],
    wrappers: ['@/layouts/Wrapper'],
  },
  {
    exact: true,
    path: '/department',
    component: '@/pages/Department/index',
    title: 'Phòng ban',
    routes: [],
    wrappers: ['@/layouts/Wrapper'],
  },
  {
    exact: true,
    path: '/department_new',
    component: '@/pages/DepartmentInfo/index',
    title: 'Tạo phòng ban',
    routes: [],
    wrappers: ['@/layouts/Wrapper'],
  },
  {
    exact: true,
    path: '/department_edit/:id/:name',
    component: '@/pages/DepartmentInfo/index',
    title: 'Tạo phòng ban',
    routes: [],
    wrappers: ['@/layouts/Wrapper'],
  },
  {
    exact: true,
    path: '/position',
    component: '@/pages/Position/index',
    title: 'Vị trí',
    routes: [],
    wrappers: ['@/layouts/Wrapper'],
  },
  {
    exact: true,
    path: '/position_new',
    component: '@/pages/PositionInfo/index',
    title: 'Vị trí',
    routes: [],
    wrappers: ['@/layouts/Wrapper'],
  },
  {
    exact: true,
    path: '/position_edit/:id',
    component: '@/pages/PositionInfo/index',
    title: 'Vị trí',
    routes: [],
    wrappers: ['@/layouts/Wrapper'],
  },
  {
    exact: true,
    path: '/policy',
    component: '@/pages/Policy/index',
    title: 'Điều khoản',
    routes: [],
    wrappers: ['@/layouts/Wrapper'],
  },
  {
    exact: true,
    path: '/policy_new',
    component: '@/pages/PolicyInfo/index',
    title: 'Tạo điều khoản',
    routes: [],
    wrappers: ['@/layouts/Wrapper'],
  },
  {
    exact: true,
    path: '/policy_edit/:id',
    component: '@/pages/PolicyInfo/index',
    title: 'Điều khoản',
    routes: [],
    wrappers: ['@/layouts/Wrapper'],
  },
  {
    exact: true,
    path: '/new',
    component: '@/pages/New/index',
    title: 'Tin tức',
    routes: [],
    wrappers: ['@/layouts/Wrapper'],
  },
  {
    exact: true,
    path: '/new_new',
    component: '@/pages/NewInfo/index',
    title: 'Tạo tin tức',
    routes: [],
    wrappers: ['@/layouts/Wrapper'],
  },
  {
    exact: true,
    path: '/new_edit/:id',
    component: '@/pages/NewInfo/index',
    title: 'Chỉnh sửa tin tức',
    routes: [],
    wrappers: ['@/layouts/Wrapper'],
  },
  {
    exact: true,
    path: '/list-salary',
    component: '@/pages/ListSalary/index',
    title: 'Danh sách lương nhân viên',
    routes: [],
    wrappers: ['@/layouts/Wrapper'],
  },
  {
    exact: true,
    path: '/salary',
    component: '@/pages/Salary/index',
    title: 'Tính lương nhân viên',
    routes: [],
    wrappers: ['@/layouts/Wrapper'],
  },
  {
    exact: true,
    path: '/dot_infomation',
    component: '@/pages/DotInfo/index',
    title: 'Danh sách chấm công',
    routes: [],
    wrappers: ['@/layouts/Wrapper'],
  },
  {
    exact: true,
    path: '/Checkin',
    component: '@/pages/Checkin/index',
    title: 'Checkin',
    routes: [],
    wrappers: ['@/layouts/Wrapper'],
  },
  {
    exact: true,
    path: '/user-user',
    component: '@/pages/UserUser/index',
    title: 'Danh sách nhân viên',
    routes: [],
    wrappers: ['@/layouts/Wrapper'],
  },
  {
    exact: true,
    path: '/NewUser',
    component: '@/pages/NewUser/index',
    title: 'Danh sách tin tức',
    routes: [],
    wrappers: ['@/layouts/Wrapper'],
  },
  {
    exact: true,
    path: '/DepartmentUser',
    component: '@/pages/DepartmentUser/index',
    title: 'Danh sách phòng ban',
    routes: [],
    wrappers: ['@/layouts/Wrapper'],
  },
];
export default [
  {
    exact: true,
    path: '/login',
    component: '@/layouts/AuthLayout/index',
    title: 'Login',
    wrappers: ['@/layouts/Wrapper'],
    routes: [
      { exact: true, path: '/login', component: '@/pages/SignIn/index' },
      { exact: true, path: '/reset-pass', component: '@/pages/SignIn/index' },
    ],
  },
  {
    exact: true,
    path: '/reset-pass/:email/:token',
    component: '@/layouts/AuthLayout/index',
    title: 'Login',
    wrappers: ['@/layouts/Wrapper'],
    routes: [
      { exact: true, path: '/reset-pass/:email/:token', component: '@/pages/ResetPass/index' },
    ],
  },
  {
    exact: false,
    path: '/',
    component: '@/layouts/MainLayout',
    wrappers: ['@/layouts/Wrapper'],
    routes: authRoutes,
  },
];
